# Generated by Django 5.0.2 on 2024-02-23 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdName', models.CharField(max_length=50)),
                ('tdDes', models.TextField(blank=True, null=True)),
                ('tdStatus', models.BooleanField(default=False)),
                ('tdDate', models.DateTimeField(auto_now_add=True)),
                ('tdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
